---
- hosts: all
  become: true
  tasks:
    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        create: yes
        block: |
          10.128.0.24 mas1
          10.128.0.29 mas2
          10.128.0.25 mas3
          10.128.0.24 work1
          10.128.0.27 work2
          10.128.0.31 work3