apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web
  labels: # Метки в формате key: value
    key: value
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: web
    image: jupelok/otus:0.0.1