apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"